[
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
		{
			"key_event": {
				"key": 6,
				"mod": 65,
				"ignore_mod": false,
				"use_repeat": false,
				"ctx": 0
			},
			"action": {
				"type": 2
			}
		}
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
		{
			"key_event": {
				"key": 11,
				"mod": 0,
				"ignore_mod": true,
				"use_repeat": true,
				"ctx": 0
			},
			"action": {
				"type": 2
			}
		}
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
		{
			"key_event": {
				"key": 21,
				"mod": 0,
				"ignore_mod": false,
				"use_repeat": false,
				"ctx": 0
			},
			"action": {
				"type": 0,
				"value": 10.00000000
			}
		},
		{
			"key_event": {
				"key": 21,
				"mod": 64,
				"ignore_mod": false,
				"use_repeat": false,
				"ctx": 0
			},
			"action": {
				"type": 0,
				"value": -10.00000000
			}
		}
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
		{
			"key_event": {
				"key": 41,
				"mod": 0,
				"ignore_mod": false,
				"use_repeat": false,
				"ctx": 0
			},
			"action": {
				"type": 6
			}
		}
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[
		{
			"key_event": {
				"key": 226,
				"mod": 256,
				"ignore_mod": false,
				"use_repeat": false,
				"ctx": 0
			},
			"action": {
				"type": 0,
				"up": false
			}
		}
	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	],
	[

	]
]